server.port: 8181
spring.cloud.stream:
  bindings:
    appliance-outbound:
      destination: appliance-topic
  kafka.streams.binder:
    brokers: localhost:9092
    configuration:
      commit.interval.ms: 1000
    serdeError: logAndContinue
  kafka.bindings:
    appliance-outbound:
      producer:
        configuration:
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: com.example.Ordering.models.cOrder